name: Push to Heroku

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: ad1fed52-0033-4295-acbf-843a1eff9d09
      run: heroku login 
    - name: Add Heroku remote
      run: heroku git:remote -a kea-attendance
    - name: Push to Heroku
      run: git push heroku main