name: Push to Heroku

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku login 
    - name: Add Heroku remote
      run: heroku git:remote --app ${{secrets.HEROKU_APP_NAME}}
    - name: Push to Heroku
      run: git push heroku main