name: Push to Heroku

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login romanzvoda@yahoo.com
            password ad1fed52-0033-4295-acbf-843a1eff9d09
          machine git.heroku.com
            login romanzvoda@yahoo.com
            password ad1fed52-0033-4295-acbf-843a1eff9d09
        EOF
    - name: Add Heroku remote
      run: heroku git:remote --app kea-attendance
    - name: Add
      run: git add .
    - name: Commit
      run: git commit -m "deploy"
    - name: Push to Heroku
      run: git push heroku main